### ISSUE TITLE
All APIs - handle no results/errors

### ISSUE THREAD

**Issue by blahmonkey** [mikkokotila/Padma-Frontend#4]
Currently only successful API calls with non empty results are handled well. The other cases need better handling

**Comment by mikkokotila** [comment]
This opens the question about where to handle this. One option is that the API has a way to return error as JSON-like object.

**Comment by blahmonkey** [comment]
Yes, and with http error code (not 200). 

But even before that, the frontend should handle any non-200s from backend. And also empty results.
