### ISSUE TITLE
Loader animation

### ISSUE THREAD

**Issue by blahmonkey** [mikkokotila/Padma-Frontend#6]
To be used whenever an API request is in progress

**Comment by blahmonkey** [comment]
@mikkokotila Do you want to look at https://loading.io/ and select + customize something from there? Need an animated GIF

**Comment by mikkokotila** [comment]
maybe this: https://loading.io/asset/393470

**Comment by blahmonkey** [comment]
Any customization required, or have you already done that?

**Comment by blahmonkey** [comment]
Ok I see you already did. Lets go with this
